/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_block_token1 = 1,
  aux_sym_if_clause_token1 = 2,
  aux_sym_or_marker_token1 = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_BANG = 6,
  aux_sym_then_clause_token1 = 7,
  aux_sym_response_token1 = 8,
  anon_sym_POUND = 9,
  anon_sym_COMMA = 10,
  sym_tra_ref = 11,
  anon_sym_LBRACK = 12,
  aux_sym_object_ref_token1 = 13,
  anon_sym_RBRACK = 14,
  anon_sym_DOT = 15,
  sym_variable_ref = 16,
  sym_identifier = 17,
  sym_number = 18,
  anon_sym_DQUOTE = 19,
  aux_sym_string_token1 = 20,
  anon_sym_TILDE = 21,
  aux_sym_string_token2 = 22,
  sym_comment = 23,
  sym_line_comment = 24,
  sym_source_file = 25,
  sym_block = 26,
  sym_if_clause = 27,
  sym__condition_item = 28,
  sym_or_marker = 29,
  sym_condition = 30,
  sym_then_clause = 31,
  sym_response = 32,
  sym_action = 33,
  sym_call_expr = 34,
  sym__argument = 35,
  sym_object_ref = 36,
  sym_point = 37,
  sym__point_coord = 38,
  sym_string = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_if_clause_repeat1 = 41,
  aux_sym_then_clause_repeat1 = 42,
  aux_sym_response_repeat1 = 43,
  aux_sym_call_expr_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_block_token1] = "block_token1",
  [aux_sym_if_clause_token1] = "if_clause_token1",
  [aux_sym_or_marker_token1] = "or_marker_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_BANG] = "!",
  [aux_sym_then_clause_token1] = "then_clause_token1",
  [aux_sym_response_token1] = "response_token1",
  [anon_sym_POUND] = "#",
  [anon_sym_COMMA] = ",",
  [sym_tra_ref] = "tra_ref",
  [anon_sym_LBRACK] = "[",
  [aux_sym_object_ref_token1] = "object_ref_token1",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [sym_variable_ref] = "variable_ref",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_TILDE] = "~",
  [aux_sym_string_token2] = "string_token2",
  [sym_comment] = "comment",
  [sym_line_comment] = "line_comment",
  [sym_source_file] = "source_file",
  [sym_block] = "block",
  [sym_if_clause] = "if_clause",
  [sym__condition_item] = "_condition_item",
  [sym_or_marker] = "or_marker",
  [sym_condition] = "condition",
  [sym_then_clause] = "then_clause",
  [sym_response] = "response",
  [sym_action] = "action",
  [sym_call_expr] = "call_expr",
  [sym__argument] = "_argument",
  [sym_object_ref] = "object_ref",
  [sym_point] = "point",
  [sym__point_coord] = "_point_coord",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_if_clause_repeat1] = "if_clause_repeat1",
  [aux_sym_then_clause_repeat1] = "then_clause_repeat1",
  [aux_sym_response_repeat1] = "response_repeat1",
  [aux_sym_call_expr_repeat1] = "call_expr_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_block_token1] = aux_sym_block_token1,
  [aux_sym_if_clause_token1] = aux_sym_if_clause_token1,
  [aux_sym_or_marker_token1] = aux_sym_or_marker_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_BANG] = anon_sym_BANG,
  [aux_sym_then_clause_token1] = aux_sym_then_clause_token1,
  [aux_sym_response_token1] = aux_sym_response_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_tra_ref] = sym_tra_ref,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_object_ref_token1] = aux_sym_object_ref_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_variable_ref] = sym_variable_ref,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_comment] = sym_comment,
  [sym_line_comment] = sym_line_comment,
  [sym_source_file] = sym_source_file,
  [sym_block] = sym_block,
  [sym_if_clause] = sym_if_clause,
  [sym__condition_item] = sym__condition_item,
  [sym_or_marker] = sym_or_marker,
  [sym_condition] = sym_condition,
  [sym_then_clause] = sym_then_clause,
  [sym_response] = sym_response,
  [sym_action] = sym_action,
  [sym_call_expr] = sym_call_expr,
  [sym__argument] = sym__argument,
  [sym_object_ref] = sym_object_ref,
  [sym_point] = sym_point,
  [sym__point_coord] = sym__point_coord,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_if_clause_repeat1] = aux_sym_if_clause_repeat1,
  [aux_sym_then_clause_repeat1] = aux_sym_then_clause_repeat1,
  [aux_sym_response_repeat1] = aux_sym_response_repeat1,
  [aux_sym_call_expr_repeat1] = aux_sym_call_expr_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_block_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_clause_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_or_marker_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_then_clause_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_response_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_tra_ref] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_object_ref_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_variable_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_if_clause] = {
    .visible = true,
    .named = true,
  },
  [sym__condition_item] = {
    .visible = false,
    .named = true,
  },
  [sym_or_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_then_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_response] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_object_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_point] = {
    .visible = true,
    .named = true,
  },
  [sym__point_coord] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_then_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_response_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_call = 2,
  field_count = 3,
  field_func = 4,
  field_if = 5,
  field_then = 6,
  field_weight = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_call] = "call",
  [field_count] = "count",
  [field_func] = "func",
  [field_if] = "if",
  [field_then] = "then",
  [field_weight] = "weight",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 3},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_call, 0},
  [1] =
    {field_call, 1},
  [2] =
    {field_if, 0},
    {field_then, 1},
  [4] =
    {field_func, 0},
  [5] =
    {field_count, 2},
  [6] =
    {field_args, 2},
    {field_func, 0},
  [8] =
    {field_args, 1},
  [9] =
    {field_args, 2},
    {field_args, 3, .inherited = true},
    {field_func, 0},
  [12] =
    {field_args, 0, .inherited = true},
    {field_args, 1, .inherited = true},
  [14] =
    {field_weight, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 8,
  [29] = 29,
  [30] = 10,
  [31] = 9,
  [32] = 27,
  [33] = 23,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      ADVANCE_MAP(
        '!', 35,
        '"', 68,
        '#', 40,
        '%', 26,
        '(', 33,
        ')', 34,
        ',', 41,
        '-', 23,
        '.', 49,
        '/', 5,
        '0', 65,
        '@', 24,
        '[', 43,
        ']', 48,
        '~', 75,
        'E', 15,
        'e', 15,
        'I', 13,
        'i', 13,
        'O', 20,
        'o', 20,
        'R', 10,
        'r', 10,
        'T', 14,
        't', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 35,
        ')', 34,
        ',', 41,
        '/', 5,
        'O', 61,
        'o', 61,
        'T', 55,
        't', 55,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 68,
        '%', 26,
        ')', 34,
        '-', 23,
        '/', 5,
        '0', 65,
        '@', 24,
        '[', 43,
        '~', 75,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(26);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '0') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(83);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(82);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(57);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 9:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 12:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(30);
      END_STATE();
    case 14:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 16:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 17:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(11);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      END_STATE();
    case 26:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_block_token1);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_block_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_if_clause_token1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_or_marker_token1);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_or_marker_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_then_clause_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_then_clause_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_response_token1);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_response_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_tra_ref);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_object_ref_token1);
      if (lookahead == 'x') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_object_ref_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_object_ref_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      if (lookahead == '.' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_object_ref_token1);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_variable_ref);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'x') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(72);
      if (lookahead == '/') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(71);
      if (lookahead == '/') ADVANCE(74);
      if (lookahead == '\n' ||
          lookahead == '"') ADVANCE(7);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(71);
      if (lookahead == '\n' ||
          lookahead == '"') ADVANCE(7);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(70);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(78);
      if (lookahead == '/') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '~') ADVANCE(81);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(77);
      if (lookahead == '/') ADVANCE(81);
      if (lookahead == '\n' ||
          lookahead == '~') ADVANCE(7);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(77);
      if (lookahead == '\n' ||
          lookahead == '~') ADVANCE(7);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(76);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '~') ADVANCE(81);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '~') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '~') ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 73},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 79},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_block_token1] = ACTIONS(1),
    [aux_sym_if_clause_token1] = ACTIONS(1),
    [aux_sym_or_marker_token1] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [aux_sym_then_clause_token1] = ACTIONS(1),
    [aux_sym_response_token1] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_tra_ref] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_variable_ref] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(51),
    [sym_block] = STATE(14),
    [sym_if_clause] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_if_clause_token1] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_TILDE,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(11), 3,
      sym_tra_ref,
      sym_variable_ref,
      sym_number,
    STATE(27), 5,
      sym_call_expr,
      sym__argument,
      sym_object_ref,
      sym_point,
      sym_string,
  [32] = 8,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_TILDE,
    ACTIONS(21), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(23), 3,
      sym_tra_ref,
      sym_variable_ref,
      sym_number,
    STATE(32), 5,
      sym_call_expr,
      sym__argument,
      sym_object_ref,
      sym_point,
      sym_string,
  [64] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_TILDE,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(25), 3,
      sym_tra_ref,
      sym_variable_ref,
      sym_number,
    STATE(36), 5,
      sym_call_expr,
      sym__argument,
      sym_object_ref,
      sym_point,
      sym_string,
  [93] = 7,
    ACTIONS(27), 1,
      aux_sym_or_marker_token1,
    ACTIONS(30), 1,
      anon_sym_BANG,
    ACTIONS(33), 1,
      aux_sym_then_clause_token1,
    ACTIONS(35), 1,
      sym_identifier,
    STATE(17), 1,
      sym_call_expr,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(5), 4,
      sym__condition_item,
      sym_or_marker,
      sym_condition,
      aux_sym_if_clause_repeat1,
  [119] = 7,
    ACTIONS(38), 1,
      aux_sym_or_marker_token1,
    ACTIONS(40), 1,
      anon_sym_BANG,
    ACTIONS(42), 1,
      aux_sym_then_clause_token1,
    ACTIONS(44), 1,
      sym_identifier,
    STATE(17), 1,
      sym_call_expr,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(7), 4,
      sym__condition_item,
      sym_or_marker,
      sym_condition,
      aux_sym_if_clause_repeat1,
  [145] = 7,
    ACTIONS(38), 1,
      aux_sym_or_marker_token1,
    ACTIONS(40), 1,
      anon_sym_BANG,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(46), 1,
      aux_sym_then_clause_token1,
    STATE(17), 1,
      sym_call_expr,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(5), 4,
      sym__condition_item,
      sym_or_marker,
      sym_condition,
      aux_sym_if_clause_repeat1,
  [171] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(48), 3,
      aux_sym_or_marker_token1,
      aux_sym_then_clause_token1,
      sym_identifier,
    ACTIONS(50), 3,
      anon_sym_RPAREN,
      anon_sym_BANG,
      anon_sym_COMMA,
  [186] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(52), 3,
      aux_sym_or_marker_token1,
      aux_sym_then_clause_token1,
      sym_identifier,
    ACTIONS(54), 3,
      anon_sym_RPAREN,
      anon_sym_BANG,
      anon_sym_COMMA,
  [201] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(56), 3,
      aux_sym_or_marker_token1,
      aux_sym_then_clause_token1,
      sym_identifier,
    ACTIONS(58), 3,
      anon_sym_RPAREN,
      anon_sym_BANG,
      anon_sym_COMMA,
  [216] = 5,
    ACTIONS(62), 1,
      sym_identifier,
    STATE(26), 1,
      sym_call_expr,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(60), 2,
      aux_sym_block_token1,
      aux_sym_response_token1,
    STATE(11), 2,
      sym_action,
      aux_sym_response_repeat1,
  [235] = 5,
    ACTIONS(67), 1,
      sym_identifier,
    STATE(26), 1,
      sym_call_expr,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(65), 2,
      aux_sym_block_token1,
      aux_sym_response_token1,
    STATE(11), 2,
      sym_action,
      aux_sym_response_repeat1,
  [254] = 5,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      aux_sym_if_clause_token1,
    STATE(40), 1,
      sym_if_clause,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(13), 2,
      sym_block,
      aux_sym_source_file_repeat1,
  [272] = 5,
    ACTIONS(7), 1,
      aux_sym_if_clause_token1,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    STATE(40), 1,
      sym_if_clause,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(13), 2,
      sym_block,
      aux_sym_source_file_repeat1,
  [290] = 3,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(76), 3,
      aux_sym_or_marker_token1,
      aux_sym_then_clause_token1,
      sym_identifier,
  [303] = 4,
    ACTIONS(80), 1,
      aux_sym_block_token1,
    ACTIONS(82), 1,
      aux_sym_response_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(21), 2,
      sym_response,
      aux_sym_then_clause_repeat1,
  [318] = 3,
    ACTIONS(86), 1,
      anon_sym_BANG,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(84), 3,
      aux_sym_or_marker_token1,
      aux_sym_then_clause_token1,
      sym_identifier,
  [331] = 4,
    ACTIONS(88), 1,
      sym_identifier,
    STATE(26), 1,
      sym_call_expr,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(12), 2,
      sym_action,
      aux_sym_response_repeat1,
  [346] = 3,
    ACTIONS(92), 1,
      anon_sym_BANG,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(90), 3,
      aux_sym_or_marker_token1,
      aux_sym_then_clause_token1,
      sym_identifier,
  [359] = 5,
    ACTIONS(94), 1,
      aux_sym_object_ref_token1,
    ACTIONS(96), 1,
      sym_variable_ref,
    ACTIONS(98), 1,
      sym_number,
    STATE(53), 1,
      sym__point_coord,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [376] = 4,
    ACTIONS(100), 1,
      aux_sym_block_token1,
    ACTIONS(102), 1,
      aux_sym_response_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(21), 2,
      sym_response,
      aux_sym_then_clause_repeat1,
  [391] = 3,
    ACTIONS(82), 1,
      aux_sym_response_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(16), 2,
      sym_response,
      aux_sym_then_clause_repeat1,
  [403] = 4,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    STATE(25), 1,
      aux_sym_call_expr_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [417] = 3,
    STATE(47), 1,
      sym__point_coord,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(109), 2,
      sym_variable_ref,
      sym_number,
  [429] = 4,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    ACTIONS(113), 1,
      anon_sym_COMMA,
    STATE(25), 1,
      aux_sym_call_expr_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [443] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(116), 3,
      aux_sym_block_token1,
      aux_sym_response_token1,
      sym_identifier,
  [453] = 4,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(118), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      aux_sym_call_expr_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [467] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(48), 3,
      aux_sym_block_token1,
      aux_sym_response_token1,
      sym_identifier,
  [477] = 3,
    ACTIONS(120), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(122), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [489] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(56), 3,
      aux_sym_block_token1,
      aux_sym_response_token1,
      sym_identifier,
  [499] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(52), 3,
      aux_sym_block_token1,
      aux_sym_response_token1,
      sym_identifier,
  [509] = 4,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      aux_sym_call_expr_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [523] = 4,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_call_expr_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [537] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(128), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [546] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(130), 2,
      ts_builtin_sym_end,
      aux_sym_if_clause_token1,
  [555] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(132), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [564] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(134), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [573] = 3,
    ACTIONS(136), 1,
      sym_identifier,
    STATE(19), 1,
      sym_call_expr,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [584] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(138), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [593] = 3,
    ACTIONS(140), 1,
      aux_sym_then_clause_token1,
    STATE(42), 1,
      sym_then_clause,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [604] = 2,
    ACTIONS(142), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [612] = 2,
    ACTIONS(144), 1,
      aux_sym_block_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [620] = 2,
    ACTIONS(146), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [628] = 2,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [636] = 2,
    ACTIONS(150), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [644] = 2,
    ACTIONS(152), 1,
      aux_sym_string_token1,
    ACTIONS(154), 2,
      sym_comment,
      sym_line_comment,
  [652] = 2,
    ACTIONS(156), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [660] = 2,
    ACTIONS(158), 1,
      aux_sym_string_token2,
    ACTIONS(154), 2,
      sym_comment,
      sym_line_comment,
  [668] = 2,
    ACTIONS(160), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [676] = 2,
    ACTIONS(120), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [684] = 2,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [692] = 2,
    ACTIONS(164), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [700] = 2,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [708] = 2,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [716] = 2,
    ACTIONS(168), 1,
      anon_sym_TILDE,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
  [724] = 2,
    ACTIONS(170), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 119,
  [SMALL_STATE(7)] = 145,
  [SMALL_STATE(8)] = 171,
  [SMALL_STATE(9)] = 186,
  [SMALL_STATE(10)] = 201,
  [SMALL_STATE(11)] = 216,
  [SMALL_STATE(12)] = 235,
  [SMALL_STATE(13)] = 254,
  [SMALL_STATE(14)] = 272,
  [SMALL_STATE(15)] = 290,
  [SMALL_STATE(16)] = 303,
  [SMALL_STATE(17)] = 318,
  [SMALL_STATE(18)] = 331,
  [SMALL_STATE(19)] = 346,
  [SMALL_STATE(20)] = 359,
  [SMALL_STATE(21)] = 376,
  [SMALL_STATE(22)] = 391,
  [SMALL_STATE(23)] = 403,
  [SMALL_STATE(24)] = 417,
  [SMALL_STATE(25)] = 429,
  [SMALL_STATE(26)] = 443,
  [SMALL_STATE(27)] = 453,
  [SMALL_STATE(28)] = 467,
  [SMALL_STATE(29)] = 477,
  [SMALL_STATE(30)] = 489,
  [SMALL_STATE(31)] = 499,
  [SMALL_STATE(32)] = 509,
  [SMALL_STATE(33)] = 523,
  [SMALL_STATE(34)] = 537,
  [SMALL_STATE(35)] = 546,
  [SMALL_STATE(36)] = 555,
  [SMALL_STATE(37)] = 564,
  [SMALL_STATE(38)] = 573,
  [SMALL_STATE(39)] = 584,
  [SMALL_STATE(40)] = 593,
  [SMALL_STATE(41)] = 604,
  [SMALL_STATE(42)] = 612,
  [SMALL_STATE(43)] = 620,
  [SMALL_STATE(44)] = 628,
  [SMALL_STATE(45)] = 636,
  [SMALL_STATE(46)] = 644,
  [SMALL_STATE(47)] = 652,
  [SMALL_STATE(48)] = 660,
  [SMALL_STATE(49)] = 668,
  [SMALL_STATE(50)] = 676,
  [SMALL_STATE(51)] = 684,
  [SMALL_STATE(52)] = 692,
  [SMALL_STATE(53)] = 700,
  [SMALL_STATE(54)] = 708,
  [SMALL_STATE(55)] = 716,
  [SMALL_STATE(56)] = 724,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_clause_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_clause, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_clause, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expr, 3, 0, 4),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expr, 3, 0, 4),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expr, 5, 0, 8),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expr, 5, 0, 8),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expr, 4, 0, 6),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expr, 4, 0, 6),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_response_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_response_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response, 4, 0, 10),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_or_marker, 4, 0, 5),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or_marker, 4, 0, 5),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_then_clause, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 1, 0, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 1, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 2, 0, 2),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 2, 0, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_then_clause_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_then_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expr_repeat1, 2, 0, 9),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expr_repeat1, 2, 0, 9), SHIFT_REPEAT(4),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 1, 0, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_point, 5, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expr_repeat1, 2, 0, 7),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_ref, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [162] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_baf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "baf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
