env:
    browser: false
    es2021: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - "@typescript-eslint"
rules:
    "@typescript-eslint/no-empty-interface": "off"
