/**
 * Pure completion filtering for the TD TypeScript plugin.
 * Filters ES2020 lib names from .td file completions, and filters
 * TD runtime names from non-.td file completions.
 */

/**
 * Completion entry kinds that are always kept regardless of name.
 * Member kinds come from dot-access on specific types (not global scope).
 * Local kinds are user-defined symbols in the current scope.
 * Keywords are TypeScript language keywords (if, else, string, number, etc.).
 */
const ALWAYS_ALLOWED_KINDS: ReadonlySet<string> = new Set([
    "keyword",          // TypeScript keywords (if, else, string, number, etc.)
    "property",         // memberVariableElement -- dot-access members
    "method",           // memberFunctionElement -- dot-access methods
    "getter",           // memberGetAccessorElement
    "setter",           // memberSetAccessorElement
    "constructor",      // constructorImplementationElement
    "call",             // callSignatureElement
    "index",            // indexSignatureElement
    "construct",        // constructSignatureElement
    "local var",        // localVariableElement -- user-defined local variable
    "local function",   // localFunctionElement -- user-defined local function
    "local class",      // localClassElement
    "parameter",        // parameterElement -- function parameter
    "label",            // label -- for goto/break targets
    "string",           // string literal completions
]);

/**
 * All names declared in TypeScript's ES2020 lib files (the full reference chain
 * from lib.es2020.d.ts). These are ES built-in globals that are irrelevant in
 * .td files and just add noise to the completion list.
 *
 * Generated by tmp/extract-lib-names.js from TypeScript 5.8 lib files.
 * Keywords (string, number, boolean, etc.) are NOT affected -- they pass through
 * via ALWAYS_ALLOWED_KINDS check on entry kind.
 */
const ES_LIB_BLOCKLIST: ReadonlySet<string> = new Set([
    "Array", "ArrayBuffer", "ArrayBufferConstructor", "ArrayBufferLike", "ArrayBufferTypes", "ArrayBufferView",
    "ArrayConstructor", "ArrayIterator", "ArrayLike", "AsyncGenerator", "AsyncGeneratorFunction", "AsyncGeneratorFunctionConstructor",
    "AsyncIterable", "AsyncIterableIterator", "AsyncIterator", "AsyncIteratorObject", "Atomics", "Awaited",
    "BigInt", "BigInt64Array", "BigInt64ArrayConstructor", "BigIntConstructor", "BigIntToLocaleStringOptions", "BigUint64Array",
    "BigUint64ArrayConstructor", "Boolean", "BooleanConstructor", "BuiltinIteratorReturn", "CallableFunction", "Capitalize",
    "ClassAccessorDecoratorContext", "ClassAccessorDecoratorResult", "ClassAccessorDecoratorTarget", "ClassDecorator", "ClassDecoratorContext", "ClassFieldDecoratorContext",
    "ClassGetterDecoratorContext", "ClassMemberDecoratorContext", "ClassMethodDecoratorContext", "ClassSetterDecoratorContext", "Collator", "CollatorConstructor",
    "CollatorOptions", "ConcatArray", "ConstructorParameters", "DataView", "DataViewConstructor", "Date",
    "DateConstructor", "DateTimeFormat", "DateTimeFormatConstructor", "DateTimeFormatOptions", "DateTimeFormatPart", "DateTimeFormatPartTypes",
    "DateTimeFormatPartTypesRegistry", "DecoratorContext", "DecoratorMetadata", "DecoratorMetadataObject", "DisplayNames", "DisplayNamesFallback",
    "DisplayNamesLanguageDisplay", "DisplayNamesOptions", "DisplayNamesType", "Error", "ErrorConstructor", "EvalError",
    "EvalErrorConstructor", "Exclude", "Extract", "FlatArray", "Float32Array", "Float32ArrayConstructor",
    "Float64Array", "Float64ArrayConstructor", "Function", "FunctionConstructor", "Generator", "GeneratorFunction",
    "GeneratorFunctionConstructor", "IArguments", "ImportAssertions", "ImportAttributes", "ImportCallOptions", "ImportMeta",
    "Infinity", "InstanceType", "Int16Array", "Int16ArrayConstructor", "Int32Array", "Int32ArrayConstructor",
    "Int8Array", "Int8ArrayConstructor", "Iterable", "IterableIterator", "Iterator", "IteratorObject",
    "IteratorResult", "IteratorReturnResult", "IteratorYieldResult", "JSON", "LDMLPluralRule", "Locale",
    "LocaleCollationCaseFirst", "LocaleHourCycleKey", "LocaleOptions", "LocalesArgument", "Lowercase", "Map",
    "MapConstructor", "MapIterator", "Math", "MethodDecorator", "NaN", "NewableFunction",
    "NoInfer", "NonNullable", "Number", "NumberConstructor", "NumberFormat", "NumberFormatConstructor",
    "NumberFormatOptions", "NumberFormatOptionsCurrencyDisplay", "NumberFormatOptionsCurrencyDisplayRegistry", "NumberFormatOptionsSignDisplay", "NumberFormatOptionsSignDisplayRegistry", "NumberFormatOptionsStyle",
    "NumberFormatOptionsStyleRegistry", "NumberFormatOptionsUseGrouping", "NumberFormatOptionsUseGroupingRegistry", "NumberFormatPart", "NumberFormatPartTypeRegistry", "NumberFormatPartTypes",
    "Object", "ObjectConstructor", "Omit", "OmitThisParameter", "ParameterDecorator", "Parameters",
    "Partial", "Pick", "PluralRuleType", "PluralRules", "PluralRulesConstructor", "PluralRulesOptions",
    "Promise", "PromiseConstructor", "PromiseConstructorLike", "PromiseFulfilledResult", "PromiseLike", "PromiseRejectedResult",
    "PromiseSettledResult", "PropertyDecorator", "PropertyDescriptor", "PropertyDescriptorMap", "PropertyKey", "Proxy",
    "ProxyConstructor", "ProxyHandler", "RangeError", "RangeErrorConstructor", "Readonly", "ReadonlyArray",
    "ReadonlyMap", "ReadonlySet", "Record", "ReferenceError", "ReferenceErrorConstructor", "RegExp",
    "RegExpConstructor", "RegExpExecArray", "RegExpMatchArray", "RegExpStringIterator", "RelativeTimeFormat", "RelativeTimeFormatLocaleMatcher",
    "RelativeTimeFormatNumeric", "RelativeTimeFormatOptions", "RelativeTimeFormatPart", "RelativeTimeFormatStyle", "RelativeTimeFormatUnit", "RelativeTimeFormatUnitSingular",
    "Required", "ResolvedCollatorOptions", "ResolvedDateTimeFormatOptions", "ResolvedDisplayNamesOptions", "ResolvedNumberFormatOptions", "ResolvedNumberFormatOptionsUseGrouping",
    "ResolvedPluralRulesOptions", "ResolvedRelativeTimeFormatOptions", "ReturnType", "Set", "SetConstructor", "SetIterator",
    "SharedArrayBuffer", "SharedArrayBufferConstructor", "String", "StringConstructor", "StringIterator", "Symbol",
    "SymbolConstructor", "SyntaxError", "SyntaxErrorConstructor", "TemplateStringsArray", "ThisParameterType", "ThisType",
    "TypeError", "TypeErrorConstructor", "TypedPropertyDescriptor", "URIError", "URIErrorConstructor", "Uint16Array",
    "Uint16ArrayConstructor", "Uint32Array", "Uint32ArrayConstructor", "Uint8Array", "Uint8ArrayConstructor", "Uint8ClampedArray",
    "Uint8ClampedArrayConstructor", "Uncapitalize", "UnicodeBCP47LocaleIdentifier", "Uppercase", "WeakKey", "WeakKeyTypes",
    "WeakMap", "WeakMapConstructor", "WeakSet", "WeakSetConstructor",
    // Global functions
    "decodeURI", "decodeURIComponent", "encodeURI", "encodeURIComponent",
    "escape", "eval", "isFinite", "isNaN", "parseFloat", "parseInt", "unescape",
    // Reflect namespace methods (not in global scope, but included for completeness)
    "apply", "construct", "defineProperty", "deleteProperty", "get", "getCanonicalLocales",
    "getOwnPropertyDescriptor", "getPrototypeOf", "has", "isExtensible", "ownKeys",
    "preventExtensions", "set", "setPrototypeOf",
]);

/** Minimal completion entry shape -- only the fields we inspect. */
export interface CompletionEntryLike {
    readonly name: string;
    readonly kind: string;
}

/**
 * Filter ES lib names from .td file completions.
 * Keeps entries whose kind is in ALWAYS_ALLOWED_KINDS or whose name
 * is not in ES_LIB_BLOCKLIST.
 * Returns a new array (immutable -- does not modify the input).
 */
export function filterEsLibCompletions<T extends CompletionEntryLike>(
    entries: readonly T[],
): T[] {
    return entries.filter(
        e => ALWAYS_ALLOWED_KINDS.has(e.kind) || !ES_LIB_BLOCKLIST.has(e.name)
    );
}

/**
 * Filter TD runtime names from non-.td file completions.
 * Returns a new array (immutable -- does not modify the input).
 */
export function filterTdRuntimeCompletions<T extends CompletionEntryLike>(
    entries: readonly T[],
    tdNames: ReadonlySet<string>,
): T[] {
    return entries.filter(e => !tdNames.has(e.name));
}
