/**
 * TypeScript Language Service Plugin for TD (.td) files.
 * - Injects td-runtime.d.ts so TD API functions are available without a tsconfig.
 * - Overrides compiler lib to exclude DOM types that clutter completions.
 * - Filters completions in .td files using a static blocklist of all names
 *   declared in TypeScript's ES2020 lib files. Keywords (string, number, etc.)
 *   and member/local symbols are kept by kind, not by name.
 * - Filters TD-specific completions out of non-.td files (e.g. .tbaf).
 *
 * Uses getScriptFileNames override on the LanguageServiceHost to ensure the
 * runtime is included in the project's program. The getExternalFiles approach
 * does not reliably work for inferred projects (standalone files without tsconfig).
 *
 * Loaded by tsserver via contributes.typescriptServerPlugins in package.json
 * (VSCode) or via tsconfig.json plugins array (other editors).
 */

import type ts from "typescript";
import * as path from "path";
import * as fs from "fs";

const TD_EXTENSION = ".td";

/**
 * Completion entry kinds that are always kept regardless of name.
 * Member kinds come from dot-access on specific types (not global scope).
 * Local kinds are user-defined symbols in the current scope.
 * Keywords are TypeScript language keywords (if, else, string, number, etc.).
 */
const ALWAYS_ALLOWED_KINDS: ReadonlySet<string> = new Set([
    "keyword",          // TypeScript keywords (if, else, string, number, etc.)
    "property",         // memberVariableElement — dot-access members
    "method",           // memberFunctionElement — dot-access methods
    "getter",           // memberGetAccessorElement
    "setter",           // memberSetAccessorElement
    "constructor",      // constructorImplementationElement
    "call",             // callSignatureElement
    "index",            // indexSignatureElement
    "construct",        // constructSignatureElement
    "local var",        // localVariableElement — user-defined local variable
    "local function",   // localFunctionElement — user-defined local function
    "local class",      // localClassElement
    "parameter",        // parameterElement — function parameter
    "label",            // label — for goto/break targets
    "string",           // string literal completions
]);

/**
 * All names declared in TypeScript's ES2020 lib files (the full reference chain
 * from lib.es2020.d.ts). These are ES built-in globals that are irrelevant in
 * .td files and just add noise to the completion list.
 *
 * Generated by tmp/extract-lib-names.js from TypeScript 5.8 lib files.
 * Keywords (string, number, boolean, etc.) are NOT affected — they pass through
 * via ALWAYS_ALLOWED_KINDS check on entry kind.
 */
const ES_LIB_BLOCKLIST: ReadonlySet<string> = new Set([
    "Array", "ArrayBuffer", "ArrayBufferConstructor", "ArrayBufferLike", "ArrayBufferTypes", "ArrayBufferView",
    "ArrayConstructor", "ArrayIterator", "ArrayLike", "AsyncGenerator", "AsyncGeneratorFunction", "AsyncGeneratorFunctionConstructor",
    "AsyncIterable", "AsyncIterableIterator", "AsyncIterator", "AsyncIteratorObject", "Atomics", "Awaited",
    "BigInt", "BigInt64Array", "BigInt64ArrayConstructor", "BigIntConstructor", "BigIntToLocaleStringOptions", "BigUint64Array",
    "BigUint64ArrayConstructor", "Boolean", "BooleanConstructor", "BuiltinIteratorReturn", "CallableFunction", "Capitalize",
    "ClassAccessorDecoratorContext", "ClassAccessorDecoratorResult", "ClassAccessorDecoratorTarget", "ClassDecorator", "ClassDecoratorContext", "ClassFieldDecoratorContext",
    "ClassGetterDecoratorContext", "ClassMemberDecoratorContext", "ClassMethodDecoratorContext", "ClassSetterDecoratorContext", "Collator", "CollatorConstructor",
    "CollatorOptions", "ConcatArray", "ConstructorParameters", "DataView", "DataViewConstructor", "Date",
    "DateConstructor", "DateTimeFormat", "DateTimeFormatConstructor", "DateTimeFormatOptions", "DateTimeFormatPart", "DateTimeFormatPartTypes",
    "DateTimeFormatPartTypesRegistry", "DecoratorContext", "DecoratorMetadata", "DecoratorMetadataObject", "DisplayNames", "DisplayNamesFallback",
    "DisplayNamesLanguageDisplay", "DisplayNamesOptions", "DisplayNamesType", "Error", "ErrorConstructor", "EvalError",
    "EvalErrorConstructor", "Exclude", "Extract", "FlatArray", "Float32Array", "Float32ArrayConstructor",
    "Float64Array", "Float64ArrayConstructor", "Function", "FunctionConstructor", "Generator", "GeneratorFunction",
    "GeneratorFunctionConstructor", "IArguments", "ImportAssertions", "ImportAttributes", "ImportCallOptions", "ImportMeta",
    "Infinity", "InstanceType", "Int16Array", "Int16ArrayConstructor", "Int32Array", "Int32ArrayConstructor",
    "Int8Array", "Int8ArrayConstructor", "Iterable", "IterableIterator", "Iterator", "IteratorObject",
    "IteratorResult", "IteratorReturnResult", "IteratorYieldResult", "JSON", "LDMLPluralRule", "Locale",
    "LocaleCollationCaseFirst", "LocaleHourCycleKey", "LocaleOptions", "LocalesArgument", "Lowercase", "Map",
    "MapConstructor", "MapIterator", "Math", "MethodDecorator", "NaN", "NewableFunction",
    "NoInfer", "NonNullable", "Number", "NumberConstructor", "NumberFormat", "NumberFormatConstructor",
    "NumberFormatOptions", "NumberFormatOptionsCurrencyDisplay", "NumberFormatOptionsCurrencyDisplayRegistry", "NumberFormatOptionsSignDisplay", "NumberFormatOptionsSignDisplayRegistry", "NumberFormatOptionsStyle",
    "NumberFormatOptionsStyleRegistry", "NumberFormatOptionsUseGrouping", "NumberFormatOptionsUseGroupingRegistry", "NumberFormatPart", "NumberFormatPartTypeRegistry", "NumberFormatPartTypes",
    "Object", "ObjectConstructor", "Omit", "OmitThisParameter", "ParameterDecorator", "Parameters",
    "Partial", "Pick", "PluralRuleType", "PluralRules", "PluralRulesConstructor", "PluralRulesOptions",
    "Promise", "PromiseConstructor", "PromiseConstructorLike", "PromiseFulfilledResult", "PromiseLike", "PromiseRejectedResult",
    "PromiseSettledResult", "PropertyDecorator", "PropertyDescriptor", "PropertyDescriptorMap", "PropertyKey", "Proxy",
    "ProxyConstructor", "ProxyHandler", "RangeError", "RangeErrorConstructor", "Readonly", "ReadonlyArray",
    "ReadonlyMap", "ReadonlySet", "Record", "ReferenceError", "ReferenceErrorConstructor", "RegExp",
    "RegExpConstructor", "RegExpExecArray", "RegExpMatchArray", "RegExpStringIterator", "RelativeTimeFormat", "RelativeTimeFormatLocaleMatcher",
    "RelativeTimeFormatNumeric", "RelativeTimeFormatOptions", "RelativeTimeFormatPart", "RelativeTimeFormatStyle", "RelativeTimeFormatUnit", "RelativeTimeFormatUnitSingular",
    "Required", "ResolvedCollatorOptions", "ResolvedDateTimeFormatOptions", "ResolvedDisplayNamesOptions", "ResolvedNumberFormatOptions", "ResolvedNumberFormatOptionsUseGrouping",
    "ResolvedPluralRulesOptions", "ResolvedRelativeTimeFormatOptions", "ReturnType", "Set", "SetConstructor", "SetIterator",
    "SharedArrayBuffer", "SharedArrayBufferConstructor", "String", "StringConstructor", "StringIterator", "Symbol",
    "SymbolConstructor", "SyntaxError", "SyntaxErrorConstructor", "TemplateStringsArray", "ThisParameterType", "ThisType",
    "TypeError", "TypeErrorConstructor", "TypedPropertyDescriptor", "URIError", "URIErrorConstructor", "Uint16Array",
    "Uint16ArrayConstructor", "Uint32Array", "Uint32ArrayConstructor", "Uint8Array", "Uint8ArrayConstructor", "Uint8ClampedArray",
    "Uint8ClampedArrayConstructor", "Uncapitalize", "UnicodeBCP47LocaleIdentifier", "Uppercase", "WeakKey", "WeakKeyTypes",
    "WeakMap", "WeakMapConstructor", "WeakSet", "WeakSetConstructor",
    // Global functions
    "decodeURI", "decodeURIComponent", "encodeURI", "encodeURIComponent",
    "escape", "eval", "isFinite", "isNaN", "parseFloat", "parseInt", "unescape",
    // Reflect namespace methods (not in global scope, but included for completeness)
    "apply", "construct", "defineProperty", "deleteProperty", "get", "getCanonicalLocales",
    "getOwnPropertyDescriptor", "getPrototypeOf", "has", "isExtensible", "ownKeys",
    "preventExtensions", "set", "setPrototypeOf",
]);

function isTdFile(fileName: string): boolean {
    return fileName.endsWith(TD_EXTENSION);
}

/**
 * Extract all declared identifier names from source text.
 * Matches both explicit (`declare function X`) and implicit (`interface X`,
 * `type X`) declarations. Anchored to line start to skip JSDoc comment text.
 */
function extractDeclaredNames(content: string): ReadonlySet<string> {
    const names = new Set<string>();
    const re = /^[ \t]*(?:declare\s+)?(?:function|interface|type|var|const|let|class|enum)\s+(\w+)/gm;
    let match;
    while ((match = re.exec(content)) !== null) {
        const name = match[1];
        if (name !== undefined) names.add(name);
    }
    return names;
}

function init(modules: { typescript: typeof ts }): ts.server.PluginModule {
    // Memoized at init() scope (shared across create() calls) because the runtime
    // path depends on __dirname (the plugin's install location), not on the project.
    // All projects using this plugin share the same runtime file.
    let runtimePath: string | undefined;
    let runtimeExists = false;
    let tdNames: ReadonlySet<string> | undefined;

    function getRuntimePath(): string {
        if (runtimePath === undefined) {
            // When installed as npm package: node_modules/@bgforge/td-plugin/out/index.js
            // td-runtime.d.ts is in node_modules/@bgforge/mls-server/out/td-runtime.d.ts
            // When bundled in VSIX: node_modules/bgforge-td-plugin/index.js
            // td-runtime.d.ts is at ../../server/out/td-runtime.d.ts
            // Try both locations.
            const vsixPath = path.resolve(__dirname, "../../server/out/td-runtime.d.ts");
            const npmPath = path.resolve(__dirname, "../../@bgforge/mls-server/out/td-runtime.d.ts");
            if (fs.existsSync(vsixPath)) {
                runtimePath = vsixPath;
                runtimeExists = true;
            } else if (fs.existsSync(npmPath)) {
                runtimePath = npmPath;
                runtimeExists = true;
            } else {
                runtimePath = vsixPath;
                runtimeExists = false;
            }
        }
        return runtimePath;
    }

    /** TD runtime names, used to filter them OUT of non-.td file completions. */
    function getTdNames(): ReadonlySet<string> {
        if (tdNames === undefined) {
            try {
                const content = fs.readFileSync(getRuntimePath(), "utf-8");
                tdNames = extractDeclaredNames(content);
            } catch {
                tdNames = new Set();
            }
        }
        return tdNames;
    }

    function create(info: ts.server.PluginCreateInfo): ts.LanguageService {
        const resolved = getRuntimePath();
        if (!runtimeExists) {
            return info.languageService;
        }

        const host = info.languageServiceHost;

        // Inject td-runtime.d.ts into the project's file list.
        // getExternalFiles does not reliably add files to inferred projects.
        const originalGetScriptFileNames = host.getScriptFileNames.bind(host);
        host.getScriptFileNames = () => {
            const files: string[] = originalGetScriptFileNames();
            if (!files.some((f: string) => isTdFile(f))) return files;
            if (files.includes(resolved)) return files;
            return [...files, resolved];
        };

        // Exclude DOM lib for projects containing .td files to avoid unrelated
        // completions (RemotePlayback, XMLHttpRequestUpload, etc.).
        // Without a tsconfig, TypeScript loads the default lib which includes DOM.
        const originalGetCompilationSettings = host.getCompilationSettings.bind(host);
        host.getCompilationSettings = () => {
            const settings = originalGetCompilationSettings();
            // Use current host method (not stale pre-override reference) so that
            // files added by other plugins or tsserver updates are seen.
            const allFiles: string[] = host.getScriptFileNames();
            if (!allFiles.some((f: string) => isTdFile(f))) {
                return settings;
            }
            return {
                ...settings,
                target: modules.typescript.ScriptTarget.ES2020,
                lib: ["lib.es2020.d.ts"],
            };
        };

        // Filter completions per file type:
        // - .td files: blocklist — hide ES lib names, keep keywords/members/locals by kind
        // - non-.td files: blocklist — remove TD runtime names that leak from shared projects
        const proxy = new Proxy(info.languageService, {
            get(target, prop, receiver) {
                if (prop === "getCompletionsAtPosition") {
                    return (fileName: string, position: number, options: ts.GetCompletionsAtPositionOptions) => {
                        const result: ts.WithMetadata<ts.CompletionInfo> | undefined =
                            target.getCompletionsAtPosition(fileName, position, options);
                        if (result === undefined) return result;

                        if (isTdFile(fileName)) {
                            const filtered = result.entries.filter(
                                e => ALWAYS_ALLOWED_KINDS.has(e.kind) || !ES_LIB_BLOCKLIST.has(e.name)
                            );
                            return { ...result, entries: filtered };
                        }

                        // In non-.td files, filter out TD runtime names
                        const names = getTdNames();
                        if (names.size === 0) return result;
                        const filtered = result.entries.filter(e => !names.has(e.name));
                        return { ...result, entries: filtered };
                    };
                }
                return Reflect.get(target, prop, receiver);
            },
        });

        return proxy;
    }

    return { create };
}

export = init;
