PRINT ~Processing dialogs~

COPY_EXISTING_REGEXP GLOB ~^.+\.dlg$~ ~override~
  PATCH_IF SOURCE_SIZE > 0x34
    AND NOT (~%SOURCE_FILE%~ STR_EQ "wsmith01.dlg") // never touch Cromwell
    AND NOT (~%SOURCE_FILE%~ STR_EQ "botsmith.dlg") // and Cespenar
    AND NOT (~%SOURCE_FILE%~ STR_EQ "thalan.dlg") // and Thalantyr
    AND NOT (~%SOURCE_FILE%~ STR_EQ "m#ruad.dlg") // and Ruad
  BEGIN
    SPRINT res ~%SOURCE_FILE%~ TO_LOWER res
    PATCH_IF VARIABLE_IS_SET $custom_regex_no_eol(~%res%~) BEGIN
      SPRINT regex $custom_regex_no_eol(~%res%~)
    END ELSE BEGIN
      SPRINT regex ~%common_regex_no_eol%~
    END
    DECOMPILE_AND_PATCH BEGIN
      LPF REPLACE_D_AND_BAF_ITEM
        STR_VAR
          old_item = ~%regex%~
          new_item = ~amul10~ //gold necklace
      END
    END
  END
BUT_ONLY


PRINT ~Processing scripts (this may take a few minutes)~
COPY_EXISTING_REGEXP GLOB ~^.+\.bcs$~ ~override~
  PATCH_IF NOT (~%SOURCE_FILE%~ STRING_MATCHES_REGEXP "^dw#.*" == 0) //skip long ass SCS scripts
    AND NOT (~%SOURCE_FILE%~ STR_EQ "ar0334.bcs") // never touch Cromwell
    AND NOT (~%SOURCE_FILE%~ STR_EQ "botsmith.bcs") // and Cespenar
  BEGIN
    SPRINT res ~%SOURCE_FILE%~ TO_LOWER res
    PATCH_IF VARIABLE_IS_SET $custom_regex(~%res%~) BEGIN
      SPRINT regex $custom_regex(~%res%~)
    END ELSE BEGIN
      SPRINT regex ~%common_regex_no_eol%~
    END
    DECOMPILE_AND_PATCH BEGIN
      LPF REPLACE_D_AND_BAF_ITEM
        STR_VAR
          old_item = ~%regex%~
          new_item = ~amul10~ //gold necklace
      END
    END
  END
BUT_ONLY
