//Thalantyr item upgrade - forbid Ring +1 upgrade to +2 when RoP+2 is unique
<<<<<<<< .../ua-inlined/thalan.d
REPLACE_TRANS_TRIGGER thalan BEGIN 82 END BEGIN END
  ~PartyHasItem("ring06")~
  ~False()~
>>>>>>>>
ACTION_IF ( (FILE_EXISTS_IN_GAME ~thsw2h01.itm~)
  AND NOT MOD_IS_INSTALLED ~ua.tp2~ (ID_OF_LABEL ~ua.tp2~ ~g_ua_allow+2~) )
BEGIN
  PRINT ~Thalantyr item upgrade~
  OUTER_SET offending_state = STATE_WHICH_SAYS 16 IN ~thalan/tra/%s/thalan.tra~ FROM ~thalan.dlg~  // Show me what you have, and I'll tell you if it can be altered.
  COMPILE EVAL ~.../ua-inlined/thalan.d~  // Make ring +1 branch always false
END
