IF
  Global("gone","LOCALS",1)
THEN
  RESPONSE #100
    NoAction()
END

IF
  True()
THEN
  RESPONSE #100
    SetGlobal("gone","LOCALS",1)
    Continue()
END


IF
  Inparty(Myself)
THEN
  RESPONSE #100
    LeaveParty()
    Continue()
END

IF
  !Allegiance(Myself,Enemy)
THEN
  RESPONSE #100
    Help()
    Shout(99)     // Non-Enemies, even party members, alert guards...
    Continue()
END



//---------------------------------------------------------------------------------
// And give approximate XP. (A bit more, it's quite the experience, after all...)
//---------------------------------------------------------------------------------

IF
  CheckstatLT(myself,10,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(10)
    Destroyself()
END

IF
  CheckstatLT(myself,20,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(20)
    Destroyself()
END

IF
  CheckstatLT(myself,50,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(50)
    Destroyself()
END

IF
  CheckstatLT(myself,100,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(100)
    Destroyself()
END

IF
  CheckstatLT(myself,200,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(200)
    Destroyself()
END

IF
  CheckstatLT(myself,500,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(500)
    Destroyself()
END

IF
  CheckstatLT(myself,1000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(1000)
    Destroyself()
END

IF
  CheckstatLT(myself,2000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(2000)
    Destroyself()
END

IF
  CheckstatLT(myself,4000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(4000)
    Destroyself()
END

IF
  CheckstatLT(myself,6000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(6000)
    Destroyself()
END

IF
  CheckstatLT(myself,8000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(8000)
    Destroyself()
END

IF
  CheckstatLT(myself,10000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(10000)
    Destroyself()
END

IF
  CheckstatLT(myself,20000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(20000)
    Destroyself()
END

IF
  CheckstatLT(myself,40000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(40000)
    Destroyself()
END

IF
  CheckstatLT(myself,60000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(60000)
    Destroyself()
END

IF
  CheckstatLT(myself,80000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(80000)
    Destroyself()
END

IF
  CheckstatLT(myself,100000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(100000)
    Destroyself()
END

IF
  CheckstatLT(myself,200000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(200000)
    Destroyself()
END

IF
  CheckstatLT(myself,300000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(300000)
    Destroyself()
END

IF
  CheckstatLT(myself,400000,XPVALUE)
THEN
  RESPONSE #100
    AddexperienceParty(400000)
    Destroyself()
END

IF
  True()
THEN
  RESPONSE #100
    AddexperienceParty(500000)
    Destroyself()
END
