DEFINE_PATCH_FUNCTION REPLACE_STRREF_TRA
  INT_VAR
    offset = 0
    old_substring_traref = 0
    new_substring_traref = 0
BEGIN
  READ_STRREF offset old_string ELSE ~~
  READ_LONG offset old_string_num
  PATCH_IF (NOT (old_string STRING_EQUAL ~~))
            AND (old_string_num != "-1")
  BEGIN
    SPRINT old_substring (AT old_substring_traref)
    SPRINT new_substring (AT new_substring_traref)
    INNER_PATCH_SAVE new_string ~%old_string%~ BEGIN
      REPLACE_TEXTUALLY ~%old_substring%~ ~%new_substring%~
    END
    SAY_EVALUATED offset ~%new_string%~
  END
END
